# Auto-generated by BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=$EDK_PATH
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=$EDK_PATH/BaseTools
fi
if [ -e $EDK_PATH/BaseTools/Bin/Linux-x86_64 ]
then
  FOUND_TOOLS_PATH_BIN=0
  for DIR in $(echo $PATH | tr ':' ' '); do
    if [ "$DIR" = "$EDK_PATH/BaseTools/Bin/Linux-x86_64" ]; then
      FOUND_TOOLS_PATH_BIN=1
    fi
  done
  if [ $FOUND_TOOLS_PATH_BIN = 0 ]
  then
    export PATH=$EDK_PATH/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
